"""Telegram bot for food logging and daily summaries."""
import asyncio
from datetime import date, datetime
from typing import Optional
from telegram import Update, Bot
from telegram.ext import (
    Application,
    CommandHandler,
    MessageHandler,
    ContextTypes,
    filters,
)
from ..config import get_settings

settings = get_settings()


class TelegramBotService:
    """Service for Telegram bot interactions."""

    def __init__(self, claude_service=None, db_session_factory=None):
        self.bot_token = settings.TELEGRAM_BOT_TOKEN
        self.chat_id = settings.TELEGRAM_CHAT_ID
        self.claude_service = claude_service
        self.db_session_factory = db_session_factory
        self.bot = None
        self.application = None

        if self.bot_token:
            self.bot = Bot(token=self.bot_token)

    async def send_message(self, message: str, chat_id: Optional[str] = None) -> bool:
        """Send a message to Telegram.

        Args:
            message: Message text to send
            chat_id: Optional chat ID (uses config default if not provided)

        Returns:
            True if message sent successfully
        """
        target_chat = chat_id or self.chat_id

        if not self.bot or not target_chat:
            print("Telegram bot not configured")
            return False

        try:
            await self.bot.send_message(
                chat_id=target_chat,
                text=message,
                parse_mode="Markdown",
            )
            return True
        except Exception as e:
            print(f"Failed to send Telegram message: {e}")
            return False

    async def send_daily_summary(
        self,
        summary: str,
        chat_id: Optional[str] = None,
    ) -> bool:
        """Send the daily health summary.

        Args:
            summary: Summary text generated by Claude
            chat_id: Optional chat ID

        Returns:
            True if sent successfully
        """
        header = f"*Daily Health Summary - {date.today().strftime('%B %d, %Y')}*\n\n"
        full_message = header + summary

        return await self.send_message(full_message, chat_id)

    def setup_handlers(self, application: Application):
        """Set up message handlers for the bot."""

        async def start_command(
            update: Update, context: ContextTypes.DEFAULT_TYPE
        ):
            """Handle /start command."""
            welcome_msg = (
                "Welcome to your Health Dashboard Bot!\n\n"
                "Commands:\n"
                "/log <food> - Log what you ate\n"
                "/today - See today's summary\n"
                "/weight - See weight progress\n"
                "/help - Show this help\n\n"
                "Or just tell me what you ate and I'll log it!"
            )
            await update.message.reply_text(welcome_msg)

        async def help_command(
            update: Update, context: ContextTypes.DEFAULT_TYPE
        ):
            """Handle /help command."""
            help_msg = (
                "*Health Dashboard Bot Help*\n\n"
                "*Logging Food:*\n"
                "Just type what you ate, e.g.:\n"
                "- 'Breakfast: 2 eggs, toast, coffee'\n"
                "- 'Had a chicken salad for lunch'\n\n"
                "*Commands:*\n"
                "/log <meal> - Log food with meal type\n"
                "/today - Today's health summary\n"
                "/weight - Weight trend\n"
                "/calories - Calorie summary\n"
                "/status - Processing status"
            )
            await update.message.reply_text(help_msg, parse_mode="Markdown")

        async def log_food_command(
            update: Update, context: ContextTypes.DEFAULT_TYPE
        ):
            """Handle /log command for food logging."""
            if not context.args:
                await update.message.reply_text(
                    "Please describe what you ate.\nExample: /log chicken salad with avocado"
                )
                return

            food_description = " ".join(context.args)
            await self._process_food_log(update, food_description, "meal")

        async def today_command(
            update: Update, context: ContextTypes.DEFAULT_TYPE
        ):
            """Handle /today command for daily summary."""
            # This would fetch data from DB and generate summary
            await update.message.reply_text(
                "Fetching today's summary... (Feature coming soon)"
            )

        async def weight_command(
            update: Update, context: ContextTypes.DEFAULT_TYPE
        ):
            """Handle /weight command."""
            await update.message.reply_text(
                "Weight tracking... (Feature coming soon)"
            )

        async def handle_message(
            update: Update, context: ContextTypes.DEFAULT_TYPE
        ):
            """Handle regular text messages - assume food logging."""
            message_text = update.message.text.lower()

            # Detect meal type from message
            meal_type = "snack"  # default
            if any(word in message_text for word in ["breakfast", "morning"]):
                meal_type = "breakfast"
            elif any(word in message_text for word in ["lunch", "noon"]):
                meal_type = "lunch"
            elif any(word in message_text for word in ["dinner", "evening"]):
                meal_type = "dinner"

            await self._process_food_log(update, update.message.text, meal_type)

        # Register handlers
        application.add_handler(CommandHandler("start", start_command))
        application.add_handler(CommandHandler("help", help_command))
        application.add_handler(CommandHandler("log", log_food_command))
        application.add_handler(CommandHandler("today", today_command))
        application.add_handler(CommandHandler("weight", weight_command))
        application.add_handler(
            MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message)
        )

    async def _process_food_log(
        self,
        update: Update,
        food_description: str,
        meal_type: str,
    ):
        """Process and log food entry."""
        if not self.claude_service:
            await update.message.reply_text(
                "Food logged (calorie estimation unavailable)"
            )
            return

        try:
            # Get calorie estimate from Claude
            estimate = await self.claude_service.estimate_food_calories(
                food_description, meal_type
            )

            if "error" in estimate:
                await update.message.reply_text(
                    f"Logged: {food_description}\n(Couldn't estimate calories)"
                )
                return

            # Format response
            response = (
                f"*{meal_type.title()} logged!*\n\n"
                f"Estimated:\n"
                f"- Calories: {estimate.get('estimated_calories', '?')} kcal\n"
                f"- Protein: {estimate.get('estimated_protein_g', '?')}g\n"
                f"- Carbs: {estimate.get('estimated_carbs_g', '?')}g\n"
                f"- Fat: {estimate.get('estimated_fat_g', '?')}g\n\n"
                f"{estimate.get('ai_notes', '')}"
            )

            await update.message.reply_text(response, parse_mode="Markdown")

            # TODO: Save to database
            # if self.db_session_factory:
            #     async with self.db_session_factory() as session:
            #         food_log = FoodLog(...)
            #         session.add(food_log)
            #         await session.commit()

        except Exception as e:
            print(f"Error processing food log: {e}")
            await update.message.reply_text(
                f"Logged: {food_description}\n(Error estimating calories)"
            )

    def run_bot(self):
        """Run the Telegram bot (blocking)."""
        if not self.bot_token:
            print("Telegram bot token not configured")
            return

        self.application = Application.builder().token(self.bot_token).build()
        self.setup_handlers(self.application)

        print("Starting Telegram bot...")
        self.application.run_polling(allowed_updates=Update.ALL_TYPES)


async def send_notification(message: str, chat_id: Optional[str] = None) -> bool:
    """Standalone function to send a Telegram notification.

    Useful for sending messages without running the full bot.
    """
    service = TelegramBotService()
    return await service.send_message(message, chat_id)
